contact_links:
  - name: Are you looking for documentation on all-data-are-local?
    url: https://maehr.github.io/all-data-are-local
    about: Please see the documentation for all-data-are-local on its GitHub Pages page.
  - name: Do you want to discuss all-data-are-local with the community?
    url: https://github.com/maehr/all-data-are-local/discussions
    about: Please see the discussions page for all-data-are-local.
blank_issues_enabled: true
